CREATE TABLE IF NOT EXISTS `users` (
  `id` BIGINT AUTO_INCREMENT COMMENT '主键ID',
  `username` VARCHAR(50) NOT NULL COMMENT '用户名',
  `role` VARCHAR(20) DEFAULT 'GUEST' COMMENT '角色: ADMIN, USER, GUEST',
  `status` VARCHAR(20) DEFAULT 'ACTIVE' COMMENT '状态: ACTIVE, DISABLED',
  `target_approver_id` BIGINT DEFAULT NULL COMMENT '申请的审批人ID',
  `password_hash` VARCHAR(255) DEFAULT NULL COMMENT '密码哈希',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '注册时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_username` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';

